name: Update Mizan Data

on:
  schedule:
    - cron: '0 * * * *' # هيشتغل كل ساعة
  workflow_dispatch: # زرار التشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
      # هنا بنربط الـ Secrets اللي عملناها بالسكريبتات
      APP_SCRIPT_URL: ${{ secrets.APP_SCRIPT_URL }}
      NEWS_SCRIPT_URL: ${{ secrets.APP_SCRIPT_URL }} # لو الأخبار في نفس الشيت استخدم نفس الرابط

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update Stocks
        run: python scraper.py

      - name: Update News
        run: python news_scraper.py
